### ISSUE TITLE
Save the active config

### ISSUE THREAD

**Issue by mehul-m-prajapati** [mehul-m-prajapati/gsoc-debun-tool#1]
- Save the active (preprocessed) config if possible via ```syslog-ng-ctl config``` command

**Comment by Kokan** [comment]
Please split this into two, as
1. part that can find the needed files (like kafka properties file); 
2. saves the active (preprocessed) config if possible via `syslog-ng-ctl config`

**Comment by mehul-m-prajapati** [comment]
PR review: https://github.com/balabit/syslog-ng/pull/2752
